repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        name: black - format package
        files: flake8_diff_only
      - id: black
        name: black - format tests
        files: tests
        args:
          - -S

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 - check package
        files: flake8_diff_only
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
          - flake8-string-format
          - flake8-comprehensions
          - flake8-quotes
          - Flake8-pyproject
          - flake8-eradicate
      - id: flake8
        name: flake8 - check tests
        files: tests
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
          - flake8-string-format
          - flake8-comprehensions
          - flake8-quotes
          - Flake8-pyproject
          - flake8-eradicate
        args:
          - --ignore=Q000

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - django==5.2.0
          - django-stubs[compatible-mypy]==5.2.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: |
          (?x)^(
              poetry.lock
          )$
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-tabs
        types:
          - python
      - id: remove-tabs
        types:
          - python

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args:
          - -formatter
          - retain_line_breaks_single=true

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        args:
          - "--blank-line-before-tag"
          - "block"
          - "--blank-line-after-tag"
          - "endblock"
          - "--line-break-after-multiline-tag"
      - id: djlint-django
        args:
          - "--ignore"
          - "T003"
